### ISSUE TITLE
I want to build me one of these, can you add a list of parts

### ISSUE THREAD

**Issue by njhurst** [kethort/esp32-bluetooth-cnc-mpg-mach4#1]
besides the esp32, what do I need to reproduce your work?

**Comment by kethort** [comment]
The PCB design files are included in the repo. I will update the repo when I have time with an updated parts list. You can get an idea of the parts list from the TCP Modbus variant of this DIY MPG Handwheel at this repo: https://github.com/kethort/esp32-cnc-mpg-handwheel-conversion-mach4. The case is 3d printed and the 3d design files are included in this repo. You can buy the PCB from JLCPCB but I don't think they stock the HT7833 voltage regulator. You can get that on ebay.

Parts:
ILI9341 TFT 2.8" display
breadboard tact switch (2 pins)
TP4056 Lithium Battery Charging Board
100PPR 6 terminal CNC Pulse Encoder 
3mm SPDT breadboard friendly micro slide switch
2 - 18650 3.7v LiPO batteries
FTDI usb to uart for programming the PCB
2.4GHz 6dBi Antenna (IPEX Connector)
4 - M3x8 screws and nuts for the display (need to drill holes in face of case)
self-tapping screws to close up the case (haven't found a 'standard' fit for this yet)
